### ISSUE TITLE
新版自选股运行问题

### ISSUE THREAD

**Issue by baiyou2014** [leafxcy/JavaScript#29]
`🔔腾讯自选股 新版, 开始!
共找到1个用户

开始初始化任务列表

❗️腾讯自选股 新版, 错误!
TypeError: Cannot read property '1' of null
    at /ql/scripts/raw_main_txstock.js:395:56
    at Array.forEach (<anonymous>)
    at getEnvParam (/ql/scripts/raw_main_txstock.js:390:34)
    at initAccountInfo (/ql/scripts/raw_main_txstock.js:438:15)
    at /ql/scripts/raw_main_txstock.js:184:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

🔔腾讯自选股 新版, 结束! 🕛 0.007 秒`
#腾讯自选股
export TxStockCookie='openid=bb&fskey=aa&wzq_qlskey=oo&wzq_qluin=xx'
export TxStockCash='5'
export TxStockNewbie='1'
export TxStockHelp='0'
export TxStockHelpOrder='0'
这样抓的

**Comment by baiyou2014** [comment]
日志有问题，但是我看有跑的任务好像
