### ISSUE TITLE
qx 跑 自选股报错

### ISSUE THREAD

**Issue by owedocker** [leafxcy/JavaScript#6]
开始初始化任务列表

❗️腾讯自选股, 错误!
TypeError: Cannot read properties of null (reading '1')
    at getEnvParam (/ql/scripts/raw_main_txstock.js:409:52)
    at initAccountInfo (/ql/scripts/raw_main_txstock.js:433:15)
    at /ql/scripts/raw_main_txstock.js:184:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

🔔腾讯自选股, 结束! 🕛 0.112 秒

**Comment by leafxcy** [comment]
CK没填对，或者链接捉错了

**Comment by SuperBambooo** [comment]
请问qx怎样跑多用户呢？我登第二个号，第一个号登信息就没了。

**Comment by yangbo525** [comment]
> 请问qx怎样跑多用户呢？我登第二个号，第一个号登信息就没了。

你找到了没有

**Comment by didididiao** [comment]
现在有些账号抓包access_token为空，直接跑脚步提示和一楼一样的错误，只能手工把access_token填写一个字符，才可以跑脚步。
